# GitHub Sponsors funding options
# github: [username]

# Open Collective
# open_collective: syslogng-dynamic

# Ko-fi
# ko_fi: username

# Tidelift
# tidelift: npm/package-name

# Community Bridge
# community_bridge: project-name

# Liberapay
# liberapay: username

# IssueHunt
# issuehunt: username

# Otechie
# otechie: username

# LFX Crowdfunding
# lfx_crowdfunding: project-name

# Custom funding URLs
# custom: ['https://example.com']
